# Generated by Django 3.1.6 on 2021-12-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='picture',
        ),
    ]
